// Auto-generated by: npm run db:types
// Or manually maintained until you run the generator

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: { id: string; email: string; full_name: string | null; plan: 'free' | 'pro' | 'advisor'; created_at: string; updated_at: string }
        Insert: { id: string; email: string; full_name?: string | null; plan?: 'free' | 'pro' | 'advisor' }
        Update: { full_name?: string | null; plan?: 'free' | 'pro' | 'advisor'; updated_at?: string }
      }
      events: {
        Row: {
          id: string; headline: string; summary: string | null; source: string | null
          source_url: string | null; published_at: string; ingested_at: string
          event_type: string | null; region: string | null; sectors: string[] | null
          sentiment_score: number | null; impact_level: 'low' | 'medium' | 'high' | null
          tickers: string[] | null; ai_processed: boolean; ai_summary: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['events']['Row'], 'id' | 'ingested_at' | 'ai_processed' | 'created_at'>
        Update: Partial<Database['public']['Tables']['events']['Insert']>
      }
      themes: {
        Row: {
          id: string; name: string; label: string; timeframe: '1m' | '3m' | '6m'
          conviction: number; momentum: string | null; brief: string | null
          supporting_event_ids: string[] | null; candidate_tickers: string[] | null
          is_active: boolean; generated_at: string; expires_at: string | null; created_at: string
        }
        Insert: Omit<Database['public']['Tables']['themes']['Row'], 'id' | 'generated_at' | 'created_at'>
        Update: Partial<Database['public']['Tables']['themes']['Insert']>
      }
      assets: {
        Row: { id: string; ticker: string; name: string; asset_type: 'stock' | 'etf' | 'crypto' | 'commodity'; sector: string | null; description: string | null; is_active: boolean; created_at: string }
        Insert: Omit<Database['public']['Tables']['assets']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['assets']['Insert']>
      }
      asset_signals: {
        Row: { id: string; asset_id: string; theme_id: string | null; signal: 'buy' | 'watch' | 'hold' | 'avoid'; score: number | null; rationale: string | null; price_at_signal: number | null; scored_at: string; created_at: string }
        Insert: Omit<Database['public']['Tables']['asset_signals']['Row'], 'id' | 'scored_at' | 'created_at'>
        Update: Partial<Database['public']['Tables']['asset_signals']['Insert']>
      }
      portfolios: {
        Row: { id: string; user_id: string; name: string; created_at: string }
        Insert: Omit<Database['public']['Tables']['portfolios']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['portfolios']['Insert']>
      }
      holdings: {
        Row: { id: string; portfolio_id: string; ticker: string; name: string | null; asset_type: string | null; quantity: number | null; avg_cost: number | null; notes: string | null; created_at: string; updated_at: string }
        Insert: Omit<Database['public']['Tables']['holdings']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['holdings']['Insert']>
      }
      advisory_memos: {
        Row: { id: string; user_id: string; portfolio_id: string | null; trigger_event_id: string | null; memo_text: string; risk_score: number | null; affected_tickers: string[] | null; generated_at: string }
        Insert: Omit<Database['public']['Tables']['advisory_memos']['Row'], 'id' | 'generated_at'>
        Update: never
      }
      alerts: {
        Row: { id: string; user_id: string; alert_type: string; title: string; body: string | null; related_event_id: string | null; related_theme_id: string | null; is_read: boolean; created_at: string }
        Insert: Omit<Database['public']['Tables']['alerts']['Row'], 'id' | 'created_at'>
        Update: { is_read?: boolean }
      }
    }
  }
}
